name        "layer-custom"
description "ElasticSearch Custom scripts from http://blogs.aws.amazon.com/application-management/post/Tx3MEVKS0A4G7R5/Deploying-Elasticsearch-with-OpsWorks"
maintainer  "amazonwebservices"
license     "Apache 2.0"
version     "1.0.0"
